version: 2.1
executors:
  jdk:
    docker:
      - image: circleci/openjdk:11-jdk-node
    working_directory: ~/workspace

aliases:
  - &attach_workspace
    attach_workspace:
      at: .

jobs:
  build:
    executor: jdk
    steps:
      - checkout
      - restore_cache:
          key: v1-sbt-dependencies-{{ checksum "build.sbt" }}

      - run:
          name: angel build
          command: |
            sbt "angel/assembly"
            mv angel/target/scala-2.13/multi-project-deploy-assembly-0.1.jar ./angel.jar

      - run:
          name: devil build
          command: |
            sbt "devil/assembly"
            mv devil/target/scala-2.13/multi-project-deploy-assembly-0.1.jar ./devil.jar

      - save_cache:
          paths:
            - ~/.cache/coursier
          key: v1-sbt-dependencies-{{ checksum "build.sbt" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  run-angel:
    executor: jdk
    steps:
      - *attach_workspace
      - run: java -jar ./angel.jar

  run-devil:
    executor: jdk
    steps:
      - *attach_workspace
      - run: java -jar ./devil.jar

workflows:
  version: 2
  build_run:
    jobs:
      - build
      - run-approval-angel:
          type: approval
          requires:
            - build
      - run-approval-devil:
          type: approval
          requires:
            - build
      - run-angel:
          requires:
            - run-approval-angel
      - run-devil:
          requires:
            - run-approval-devil